services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-todo-app
    container_name: todo_app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    networks:
      - todo_network
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: todo_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-todo_app}
      POSTGRES_USER: ${DB_USERNAME:-todo_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-todo_password}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
